/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exerciciodemo;

import org.joda.time.*;
public class App {


    
    /** 
     * @param args
     */
    public static void main(String[] args) {
        WorldTime n= new WorldTime();
        DateTimeZone zone = DateTimeZone.forID("Europe/Lisbon");
        n.getTimeByCountry(zone);
    }
}
